import localFont from 'next/font/local';
import './globals.css';
import AuthContext from '@/components/AuthContext';
import { Sora } from 'next/font/google';
// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

const sora = Sora({
  display: 'swap',
  variable: '--font-sora',
  subsets: ['latin'],
});

export const metadata = {
  title: 'StashIt',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${sora.variable} ${sora.className} antialiased`}>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
